---
title: "ParteYee"
output: html_document
date: "2026-02-08"
---
#PREPARACIÓN  
#en la sesión instalar:
library(dplyr)
library(ggplot2)

#y para tablas:
library(knitr)

#cargar datos
movies <- read.csv("movies_2026.csv", encoding = "latin1")




#PREGUNTAS

#4.1 ¿Cuáles son las 10 películas que contaron con más presupuesto?
top_budget <- movies %>%
  filter(!is.na(budget), budget > 0) %>%
  arrange(desc(budget)) %>%
  slice(1:10)

kable(
  top_budget %>% select(title, budget),
  col.names = c("Película", "Presupuesto"),
  caption = "Top 10 películas con mayor presupuesto"
)

# Respuesta
Table: Top 10 películas con mayor presupuesto

|Película                                    | Presupuesto|
|:-------------------------------------------|-----------:|
|Pirates of the Caribbean: On Stranger Tides |    3.80e+08|
|Avengers: Age of Ultron                     |    3.65e+08|
|Avengers: Endgame                           |    3.56e+08|
|Avatar: Fire and Ash                        |    3.50e+08|
|Pirates of the Caribbean: At World's End    |    3.00e+08|
|Justice League                              |    3.00e+08|
|Avengers: Infinity War                      |    3.00e+08|
|Superman Returns                            |    2.70e+08|
|Tangled                                     |    2.60e+08|
|The Lion King                               |    2.60e+08|

#Conclusión
Las películas con mayor presupuesto se deben a grandes producciones y a franquicias populares, demostrando que los estudios invierten más recursos a proyectos de alto potencial global, sin dejar de lado que un alto presupuesto no asegura el éxito de la película o aceptación del público.

#________________






#4.2 ¿Cuáles son las 10 películas que más ingresos tuvieron?
top_revenue <- movies %>%
  filter(!is.na(revenue), revenue > 0) %>%
  arrange(desc(revenue)) %>%
  slice(1:10)

kable(
  top_revenue %>% select(title, revenue),
  col.names = c("Película", "Ingresos"),
  caption = "Top 10 películas con mayores ingresos"
)


# Respuesta
Table: Top 10 películas con mayores ingresos

|Película                     |   Ingresos|
|:----------------------------|----------:|
|Avatar                       | 2847246203|
|Avengers: Endgame            | 2797800564|
|Titanic                      | 2187463944|
|Star Wars: The Force Awakens | 2068223624|
|Avengers: Infinity War       | 2046239637|
|Zootopia 2                   | 1744338246|
|Jurassic World               | 1671713208|
|The Lion King                | 1667635327|
|Spider-Man: No Way Home      | 1631853496|
|The Avengers                 | 1518815515|

# Conclusión
Las películas que tienen mayor ingreso son las producciones con gran alcance internacional y que ya pertenecen a franquicias grandes. Esto demuestra que el reconocimiento previo de la marca y el alcance influyen significativamente en el éxito de la recaudación total de la película.
#________________






#4.3 ¿Cuál es la película que más votos tuvo?
most_votes <- movies %>%
  filter(!is.na(voteCount)) %>%
  arrange(desc(voteCount)) %>%
  slice(1)

kable(
  most_votes %>% select(title, voteCount),
  col.names = c("Película", "Cantidad de votos"),
  caption = "Película con mayor número de votos"
)


# Respuesta
Table: Película con mayor número de votos

|Película  | Cantidad de votos|
|:---------|-----------------:|
|Inception |             30788|

# Conclusión
La película con mayor número de votos es Inception, indicando un alto nivel de interacción del público. La gran cantidad de votos refleja la popularidad y el alcance, sin descartar que no necesariamente tiene la mejor calificación promedio.
#________________






#4.4 ¿Cuál es la peor película de acuerdo a los votos de todos los usuarios?
worst_movie <- movies %>%
  filter(!is.na(voteAvg), voteCount >= 50) %>%
  arrange(voteAvg) %>%
  slice(1)

kable(
  worst_movie %>% select(title, voteAvg, voteCount),
  col.names = c("Película", "Calificación promedio", "Cantidad de votos"),
  caption = "Peor película según calificación promedio (mín. 50 votos)"
)

# Respuesta
Table: Peor película según calificación promedio (mín. 50 votos)

|Película             | Calificación promedio| Cantidad de votos|
|:--------------------|---------------------:|-----------------:|
|Dragonball Evolution |                   2.8|              1600|

# Conclusión
Considerando películas con al menos 50 votos, Dragonball Evolution presenta la calificación promedio más baja, indicando una recepción negativa general del público, lo que evita que valoraciones aisladas distorisionenn el análisis.
#________________







#4.5 ¿Cuántas películas se hicieron en cada año? ¿En qué año se hicieron más películas? Haga un gráfico de barras
movies_year <- movies %>%
  filter(!is.na(releaseYear)) %>%
  group_by(releaseYear) %>%
  summarise(total = n(), .groups = "drop") %>%
  arrange(desc(total))

kable(
  movies_year,
  col.names = c("Año", "Cantidad de películas"),
  caption = "Cantidad de películas producidas por año"
)



ggplot(movies_year, aes(x = factor(releaseYear), y = total)) +
  geom_col(fill = "steelblue") +
  labs(
    title = "Cantidad de películas producidas por año",
    x = "Año",
    y = "Número de películas"
  ) +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 90))



kable(
  movies_year[1, ],
  col.names = c("Año", "Cantidad"),
  caption = "Año con mayor producción de películas"
)

# Respuesta
Table: Cantidad de películas producidas por año

|  Año| Cantidad de películas|
|----:|---------------------:|
| 2025|                  7351|
| 2026|                  2537|
| 2021|                   814|
| 2018|                   628|
| 2017|                   617|
| 2019|                   611|
| 2016|                   557|
| 2020|                   531|
| 2015|                   450|
| 2014|                   432|
| 2013|                   412|
| 2011|                   361|
| 2009|                   342|
| 2012|                   328|
| 2010|                   307|
| 2008|                   282|
| 2006|                   272|
| 2007|                   266|
| 2005|                   245|
| 2004|                   229|
| 2003|                   199|
| 2002|                   185|
| 2001|                   176|
| 2000|                   132|
| 1999|                    97|
| 1998|                    92|
| 1997|                    84|
| 1993|                    83|
| 1995|                    79|
| 1996|                    76|
| 1994|                    65|
| 1992|                    63|
| 1988|                    59|
| 1989|                    59|
| 1987|                    53|
| 1991|                    50|
| 1986|                    48|
| 1985|                    47|
| 1990|                    47|
| 1984|                    41|
| 1982|                    35|
| 1981|                    30|
| 1983|                    28|
| 1978|                    22|
| 1977|                    21|
| 1979|                    20|
| 1980|                    20|
| 1973|                    19|
| 1976|                    18|
| 1963|                    16|
| 1967|                    16|
| 1971|                    16|
| 1974|                    16|
| 1975|                    16|
| 1957|                    15|
| 1968|                    15|
| 1953|                    13|
| 1962|                    13|
| 1966|                    13|
| 1972|                    13|
| 1959|                    12|
| 1970|                    12|
| 1954|                    11|
| 1956|                    11|
| 1969|                    11|
| 1961|                    10|
| 1964|                    10|
| 1958|                     9|
| 1960|                     9|
| 1952|                     8|
| 1965|                     8|
| 1940|                     7|
| 1948|                     7|
| 1955|                     7|
| 2022|                     7|
| 1951|                     6|
| 1931|                     4|
| 1939|                     4|
| 1941|                     4|
| 1942|                     4|
| 1944|                     4|
| 1946|                     4|
| 1947|                     4|
| 1950|                     4|
| 1949|                     3|
| 1925|                     2|
| 1927|                     2|
| 1943|                     2|
| 1902|                     1|
| 1920|                     1|
| 1921|                     1|
| 1922|                     1|
| 1926|                     1|
| 1929|                     1|
| 1930|                     1|
| 1932|                     1|
| 1933|                     1|
| 1935|                     1|
| 1936|                     1|
| 1937|                     1|
| 1938|                     1|

# Ver la imagen en gitgub llamada "PeliculasPorAnio"

Table: Año con mayor producción de películas

|  Año| Cantidad|
|----:|--------:|
| 2025|     7351|

# Conclusión
El análisis temporal muestra un crecimiento significativo en la producción cinematográfica a través de los años, logrando destacar el año 2025 como el año con mayor producción de películas. El aumento puede estar relacionado con la expansión de plataformas de streaming y el crecimiento de la industria a nivel global
#________________






#Extra1 ¿Existe alguna relación entre la duración de las películas y su calificación promedio?
extra_runtime <- movies %>%
  filter(
    !is.na(runtime),
    runtime > 0,
    !is.na(voteAvg),
    voteCount >= 50
  )

cor(extra_runtime$runtime, extra_runtime$voteAvg, use = "complete.obs")

ggplot(extra_runtime, aes(x = runtime, y = voteAvg)) +
  geom_point(alpha = 0.5, color = "steelblue") +
  geom_smooth(method = "lm", se = FALSE, color = "darkred") +
  labs(
    title = "Relación entre duración de la película y calificación promedio",
    x = "Duración (minutos)",
    y = "Calificación promedio"
  ) +
  theme_minimal()

# Respuesta

#Ver gráfica llamada "RelacionPeliculaCalificacion"

# Conclusión
En la gráfica se muestra como la mayoría de películas se concentran entre 80-150 minutos, y que la línea de regresión tienen una pendiente positiva suave, pero un dato importante es la gran dispersión vertical notando que las películas cortas y largas tienen ambas calificaciones altas y bajas. Debido a que los puntos azules no siguen la forma de la pendiente roja, se concluye que no hay una fuerte relación entre la duración y la calificación promedio.
#________________






#Extra2 ¿La cantidad de países de producción influye en los ingresos de las películas?
extra_countries <- movies %>%
  filter(
    !is.na(productionCountriesAmount),
    productionCountriesAmount > 0,
    !is.na(revenue),
    revenue > 0
  )

ggplot(extra_countries,
       aes(x = factor(productionCountriesAmount), y = revenue)) +
  geom_boxplot(fill = "lightgreen") +
  labs(
    title = "Ingresos según cantidad de países de producción",
    x = "Cantidad de países de producción",
    y = "Ingresos"
  ) +
  theme_minimal()


# Respuesta

#Ver gráfica llamada "IngresosPorPaises"

# Conclusión
En la gráfica se muestra una gran acumulación de puntos negros en la columna de películas que se producen en 1 o 2 países, demostrando que las películas con más ingresos son los que tienen producciones en menos países, mientras que los que tienen 6 o más no hay un patrón seguro. Podemos asegurar que coproducir películas con más países no garantizará mayores ingresos, la variabilidad es alta incluso cuando hay pocos países en la producción, por lo tanto el éxito económico dependerá en otros factores y no en la cantidad de países que la producen.







#CONCLUSIÓN
En la evidencia pasada, los resultados confirman que el éxito de una película no depende solamente de un factor, sino de diversos variables, aunque hay que destacar que variables como lo son el presupuesto, la duración o la cantidad de países que ayudan a producir las películas no muestran una gran relación con los ingresos ni calificaciones. Se puede asegurar que el éxito de una película requiere un análisis más exhaustivo en otras áreas para apoyar a tomar decisiones en la industria cinematográfica.